// Data-driven weapon definitions. All timings in seconds, spreads in
// radians, damage per hit (head multiplier applied on headshots).

export const WEAPONS = [
  {
    id: "havoc",
    name: "HAVOC",
    slot: 1,
    kind: "auto",
    damage: 34,
    headMult: 3.4,
    rpm: 620,
    mag: 25,
    reserve: 100,
    reloadTime: 2.15,
    switchTime: 0.42,
    // accuracy
    spreadBase: 0.0016,
    spreadMove: 0.030,
    spreadAir: 0.055,
    bloomPerShot: 0.0028,
    bloomMax: 0.017,
    bloomDecay: 0.055,
    // recoil (camera kick per shot)
    kickPitch: 0.0135,
    kickYaw: 0.0045,
    ads: { zoom: 1.25, spreadMult: 0.8, speedMult: 0.86 },
    tracer: "#7ffbe9",
    sound: "havoc",
    penetrates: true,
    vmKick: 0.05,
  },
  {
    id: "mauler",
    name: "MAULER",
    slot: 2,
    kind: "pump",
    damage: 13,
    headMult: 1.7,
    pellets: 8,
    rpm: 68,
    mag: 5,
    reserve: 20,
    reloadTime: 2.5,
    switchTime: 0.5,
    spreadBase: 0.045,
    spreadMove: 0.012,
    spreadAir: 0.02,
    bloomPerShot: 0,
    bloomMax: 0,
    bloomDecay: 1,
    kickPitch: 0.035,
    kickYaw: 0.008,
    falloffStart: 9,
    falloffEnd: 26,
    falloffMin: 0.3,
    ads: { zoom: 1.12, spreadMult: 0.82, speedMult: 0.88 },
    tracer: "#ffd166",
    sound: "mauler",
    penetrates: false,
    vmKick: 0.1,
  },
  {
    id: "longbow",
    name: "LONGBOW",
    slot: 3,
    kind: "bolt",
    damage: 150,
    headMult: 1.7,
    rpm: 42,
    mag: 5,
    reserve: 15,
    reloadTime: 2.7,
    switchTime: 0.62,
    spreadBase: 0.05,
    spreadMove: 0.02,
    spreadAir: 0.03,
    scopedSpread: 0.0006,
    bloomPerShot: 0,
    bloomMax: 0,
    bloomDecay: 1,
    kickPitch: 0.05,
    kickYaw: 0.006,
    ads: { zoom: 4.2, spreadMult: 1, speedMult: 0.72, scope: true },
    tracer: "#c7f0ff",
    sound: "longbow",
    penetrates: true,
    vmKick: 0.14,
  },
  {
    id: "ogre",
    name: "OGRE",
    slot: 4,
    kind: "rocket",
    damage: 118, // direct hit bonus
    headMult: 1,
    splashDamage: 92,
    splashRadius: 4.6,
    selfDamageMult: 0.4,
    rpm: 52,
    mag: 1,
    reserve: 7,
    reloadTime: 1.7,
    switchTime: 0.66,
    spreadBase: 0.004,
    spreadMove: 0.008,
    spreadAir: 0.012,
    bloomPerShot: 0,
    bloomMax: 0,
    bloomDecay: 1,
    kickPitch: 0.03,
    kickYaw: 0.004,
    projectileSpeed: 27,
    ads: { zoom: 1.15, spreadMult: 1, speedMult: 0.8 },
    tracer: "#ffb066",
    sound: "ogre",
    penetrates: false,
    vmKick: 0.12,
  },
  {
    id: "vespa",
    name: "VESPA",
    slot: 5,
    kind: "semi",
    damage: 26,
    headMult: 3,
    rpm: 440,
    mag: 12,
    reserve: 60,
    reloadTime: 1.6,
    switchTime: 0.32,
    spreadBase: 0.0014,
    spreadMove: 0.02,
    spreadAir: 0.045,
    bloomPerShot: 0.004,
    bloomMax: 0.02,
    bloomDecay: 0.09,
    kickPitch: 0.011,
    kickYaw: 0.003,
    ads: { zoom: 1.18, spreadMult: 0.8, speedMult: 0.92 },
    tracer: "#ffe9a8",
    sound: "vespa",
    penetrates: false,
    vmKick: 0.045,
  },
];

export const WEAPON_BY_ID = Object.fromEntries(WEAPONS.map((w) => [w.id, w]));
